// Generated by scripts/generate_script_loaders.py. Review before integration.
//
// No constructor and no destructor, and that is retail's shape, not an omission: the DOL has no
// `__ct__17SLdrStreamedAudioFv` or `__dt__17SLdrStreamedAudioFv` at all (`grep 17SLdrStreamedAudio
// config/G2ME01/symbols.txt` is empty), while `LoadStreamedAudio` (0x8015CDE0, 728 bytes) calls
// `__ct__20SLdrEditorPropertiesFv` and `__dt__20SLdrEditorPropertiesFv` **directly** and
// default-constructs `songFile` in place (`mNull`, 0, 0 at r1+104/108/112). That is an aggregate
// whose members are each constructed in place, so declaring a pair here made our object 648 bytes
// and cost a `bl` to a symbol retail does not define.
#ifndef _SLDRSTREAMEDAUDIO_HPP
#define _SLDRSTREAMEDAUDIO_HPP

#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"
#include "rstl/string.hpp"

struct SLdrStreamedAudio {
  SLdrEditorProperties editorProperties; // 0x255a4580
  rstl::string songFile; // 0xf6f3de1c
  bool defaultAudio; // 0x34b152c4
  float fadeInTime; // 0x90aa341f
  float fadeOutTime; // 0x7c269ebc
  int volume; // 0x80c66c37
  int softwareChannel; // 0x28f82261
  bool softwareIsMusic; // 0xd3356fe7
};

void LoadTypedefSLdrStreamedAudio(SLdrStreamedAudio& data, CInputStream& input);

#endif
