// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRRELAY_HPP
#define _SLDRRELAY_HPP

#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"

struct SLdrRelay {
  // No user-declared constructor or destructor, for the reason SLdrAreaAttributes and
  // SLdrTimeKeyframe record: retail's loader (0x800B8EFC) calls
  // __ct__20SLdrEditorPropertiesFv on the `editorProperties` member in place and
  // __dt__20SLdrEditorPropertiesFv on the way out, never a __ct__/__dt__ for the
  // aggregate itself. True of all 201 generated SLdr* headers; see
  // docs/research/missing_classes.md.
  SLdrEditorProperties editorProperties; // 0x255a4580
  bool oneShot; // 0xead7b7bb
};

#endif
