// Carved out of an unclaimed dtk `auto_*` range.  Every number here is measured: the addresses
// and sizes come from `config/G2ME01/symbols.txt`, the two instructions are retail's own in
// `build/G2ME01/asm/MetroidPrime/ScriptLoader/Carve80229EAC.s:9-12` (dtk's listing for this
// claim, with the symbol named there), and the body below is the C those bytes are the
// compilation of.  Before the carve they were the last `.fn` block of dtk's
// `auto_03_80229BC4_text.s`; that listing is regenerated by the split described below.
//
// .text 0x80229EAC..0x80229EB4, 0x8 = 8 bytes, 1 function:
//
//   fn_80229EAC    0x80229EAC  0x8    stw     r3, lbl_80419590@sda21(r0)
//                                          blr
//
// **What it is: one more loader-slot setter of the ScriptLoader family.**  `symbols.txt:9827`
// gives `fn_80229EAC = .text:0x80229EAC; // type:function size:0x8 align:4`, and the shape is
// byte-identical to the landed `fn_80227530` and `fn_80227538` (`Carve80227530.c`),
// `fn_80232834` (`Carve80232834.c`) and `fn_80232868` (`Carve80232868.c`): store the argument
// into a loader pointer's `.sbss` slot and return.  It never reads back what it stores, so it
// needs the slot's address only, not its element type.
//
// **Who calls it, and what the argument is.**  Every call site is in a REL module that imports
// the DOL function by its retail name.  There is exactly one such module, module 25
// (`config/G2ME01/config.yml:137-138`, `files/RelProd/GeomBlobV2.rel`, sha1
// `6aac53ef251d4fc41f0b07133dc710c7e0f567cc`), and both of its call sites are in
// `build/G2ME01/GeomBlobV2/asm/MetroidPrime/ScriptObjects/CGeomBlobV2Rel.s`:
//
//   * `RELExit` (0x2414): `li r3, 0x0` on line 27, the call on line 29 - the module tears its
//     registration down on the way out.
//   * `fn_25_2460` (0x2460): `lis r3, lbl_25_bss_0@ha` (line 55) /
//     `stwu r0, lbl_25_bss_0@l(r3)` (line 58), the call on line 59, with r3 still holding the
//     slot address it just wrote through - `&lbl_25_bss_0`, the module's own 4-byte record whose
//     word 0 is its entity loader `fn_25_2490`.  So the DOL slot holds a *pointer to* a loader
//     slot, which is why `src/MetroidPrime/ScriptObjects/CGeomBlobV2Rel.cpp:104` (the module's
//     own head, already landed) declares this function as
//     `void fn_80229EAC(FScriptLoader* loader)` and hands it `&lbl_25_bss_0`.
//
// **The slot is claimed by no unit of ours.**  `lbl_80419590` is `.sbss 0x80419590`
// (`symbols.txt:20768`, `size:0x8 data:4byte`); it sits in the `.sbss` gap between
// `gLoader_RsfAudio` (`RsfAudio.cpp` ends 0x80419590) and `gLoader_IngPuddle` (`IngPuddle.cpp`
// starts 0x80419598), so the matching build takes it from dtk's own
// `auto_10_80419590_sbss.o`.  `grep -rn lbl_80419590 src/ build/G2ME01/asm/ build/G2ME01/*/asm/`
// finds no reader: in `src/` only two comments (`CGeomBlobV2Rel.cpp:31,104`), in the DOL's own
// listings only the store below and dtk's `auto_10_80419590_sbss.s` definition, and nothing at
// all in the 86 modules' listings - no module imports the slot itself.  So this unit claims
// `.text` only and takes it `extern`.  The port,
// which links our sources and not dtk's objects, therefore loses it, and the host-only definition
// at the end of this file is what keeps the port's undefined count where it was.
//
// Source order is **descending by address** and that is load-bearing: mwcceppc emits function
// definitions in *reverse* source order and mwldeppc keeps the object's `.text` order verbatim,
// so an ascending file is a permuted `.text` - 100.00% per function and a broken DOL, with the
// link still succeeding.  Only `tools/flip_test.sh` catches that.
//
// Retail names none of these.  `symbols.txt` carries the `fn_<addr>` placeholder and this file
// reproduces that symbol verbatim, so the definition has to stay C: a C++ one would mangle to
// `_Z<len>fn_80229EACv` and both the DOL link and module 25's `bl fn_80229EAC` would pair
// nothing.  That is also why the unit is a `.c` rather than a `.cpp`.
//
// **Why its own unit, and what the split does.**  The dtk auto unit it comes out of is
// `auto_03_80229BC4_text.s` (`# 0x80229BC4..0x80229EB4 | size: 0x2F0`, nine functions); the
// nearest claimed units on either side are `Carve80229BBC.c` (ends 0x80229BC4) and
// `IngPuddle.cpp` (starts 0x80229EB4), and the eight functions between them are not trivial, so
// nothing else can carry these 8 bytes.  Claiming 0x80229EAC..0x80229EB4 splits that auto unit
// and nothing else: after the build its listing reads `# 0x80229BC4..0x80229EAC | size: 0x2E8`
// with **eight** functions, and `build/report.json` still lists it under the same name - an auto
// unit is named by its *start* address, so a carve at its end only shortens it, while
// `docs/goal-notes/carve-801e5230.md` records the middle case, where the tail came back under a
// new name.
//
// The directory is retail's own, taken from the nearest claimed range: this address is 8 bytes
// before the start of `MetroidPrime/ScriptLoader/IngPuddle.cpp`, so the code is that unit's
// neighbourhood.  For an anonymous function that is the only evidence there is, and it beats a
// lane picking the directory it happened to own.

/** `.sbss 0x80419590`, `symbols.txt:20768`, `size:0x8 data:4byte`: the loader slot module 25's
 *  second loader (GeomBlobV2's) registers into.  Claimed by no unit of ours, so the matching
 *  build takes it from dtk's own `auto_10_80419590_sbss.o`; this file only stores into it. */
extern void* lbl_80419590;

/** GeomBlobV2's registration (module 25): `loader` is `&lbl_25_bss_0`, the module's own 4-byte
 *  record holding its entity loader; `nullptr` is what `RELExit` passes on the way out. */
void fn_80229EAC(void* loader) { lbl_80419590 = loader; }

#ifndef __MWERKS__
// Host-only definition of the one symbol this unit references that nothing else in `src/`
// defines.  The matching build does not compile this block, so `main.dol` still takes the real
// 0x80419590 from dtk's auto object above and the function keeps its retail bytes.  Without it
// the port's flat link - which carries our sources and not dtk's objects - loses
// `lbl_80419590`, and `tools/link_check.sh --strict`, whose verdict `tools/probe_sources.sh`
// reports, names it as a new undefined symbol.  Zero-initialised on purpose and unreferenced by
// the port: nothing in `src/` reads it.  The guard is `__MWERKS__` rather than `TARGET_PC` for
// the reason `src/MetroidPrime/Cameras/Carve801E7C14.c` records - the thing that must not happen
// is a second definition in the matching build, where dtk's `auto_10_80419590_sbss.o` owns the
// slot.
void* lbl_80419590 = 0;
#endif
