// Generated by scripts/generate_script_loaders.py. Review before integration.
#include "MetroidPrime/ScriptLoader/SLdrTweakSlideShow.hpp"

SLdrTweakSlideShow::SLdrTweakSlideShow() : instanceName(), pakFile(), font(), fontColor(CColor(0.0f, 0.0f, 0.0f, 1.0f)), fontOutlineColor(CColor(0.0f, 0.0f, 0.0f, 1.0f)), unknown_0xd398dac2(50.0f), unknown_0x03757d08(50.0f), translationMultiplier(10.0f), scaleMultiplier(10.0f), slideShowDelay(3.0f), helpFrameColor(CColor(0.0f, 0.0f, 0.0f, 1.0f)), helpTransitionTime(1.0f), slideBlendTime(0.5f), slideNumberHideDelay(3.0f), slideNumberTransitionTime(0.5f), fadeInTime(0.001f), fadeOutTime(2.0f), stringResName() {
}

SLdrTweakSlideShow::~SLdrTweakSlideShow() {}

