// Generated by scripts/generate_script_loaders.py. Review before integration.
#include "MetroidPrime/ScriptLoader/SLdrTweakCameraBob.hpp"

SLdrTweakCameraBob::SLdrTweakCameraBob() : instanceName(), cameraBobExtentX(0.07f), cameraBobExtentY(0.14f), cameraBobPeriod(0.38999999f), orbitBobScale(0.76999998f), maxOrbitBobScale(0.80000001f), slowSpeedPeriodScale(0.30000001f), targetMagnitudeTrackingRate(0.1f), landingBobSpringConstant(150.0f), viewWanderRadius(0.1f), viewWanderSpeedMin(0.1f), viewWanderSpeedMax(0.40000001f), viewWanderRollVariation(0.30000001f), gunBobMagnitude(0.22f), helmetBobMagnitude(1.0f) {
}

SLdrTweakCameraBob::~SLdrTweakCameraBob() {}

