set(revision "source-snapshot")
find_program(GIT_EXECUTABLE git)
if(GIT_EXECUTABLE)
    execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" rev-parse --show-toplevel
        OUTPUT_VARIABLE git_root OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
    if(git_root STREQUAL SOURCE_DIR)
        execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" rev-parse --short=12 HEAD
            OUTPUT_VARIABLE revision OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
        execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" diff --quiet HEAD --
            RESULT_VARIABLE dirty ERROR_QUIET)
        if(NOT dirty EQUAL 0)
            string(APPEND revision "-dirty")
        endif()
    endif()
endif()
set(content "#pragma once\n#define MP_BUILD_REVISION \"${revision}\"\n")
set(previous "")
if(EXISTS "${OUTPUT_HEADER}")
    file(READ "${OUTPUT_HEADER}" previous)
endif()
if(NOT previous STREQUAL content)
    get_filename_component(output_dir "${OUTPUT_HEADER}" DIRECTORY)
    file(MAKE_DIRECTORY "${output_dir}")
    file(WRITE "${OUTPUT_HEADER}" "${content}")
endif()
